// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData } from "./tables/Position.sol";
import { Wall, WallData } from "./tables/Wall.sol";
